### ISSUE TITLE
generate composite schema from process instance

### ISSUE THREAD

**Issue by eagmon** [vivarium-collective/process-bigraph#14]
Process's `schema` method provides information that can be used for a composite schema, rather than having to declare it redundantly. "Filling" if you give the process instance but not a composite schema. If you do give a composite schema, then validate the process matches.

**Comment by prismofeverything** [comment]
A few steps:

* Initialize process
* Generate schema
* project schema using wires to construct composition (if wires are not provided, connect them to stores with those port names)
* validate schema matches state.

**Comment by prismofeverything** [comment]
In general, Composite will receive some composition and some state, and can fill bidirectionally.
